services:
  namenode:
    image: apache/hadoop:3.4
    container_name: hadoop-namenode
    hostname: namenode
    command: ["hdfs", "namenode"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9870:9870
      - 8020:8020
      - 9000:9000
    environment: &environment
      - ENSURE_NAMENODE_DIR="/tmp/hadoop-root/dfs/name"
      - CORE-SITE.XML_fs.defaultFS="hdfs://hadoop-namenode"
      - CORE-SITE.XML_fs.default.name="hdfs://hadoop-namenode"
      - HDFS-SITE.XML_dfs.namenode.rpc-address="hadoop-namenode:8020"
      - HDFS-SITE.XML_dfs.replication="2"
      - MAPRED-SITE.XML_mapreduce.framework.name="yarn"
      - HDFS-SITE.XML_dfs.permissions.enabled="false"
      - HDFS-SITE.XML_dfs.permissions.superusergroup="supergroup"
      - CORE-SITE.XML_hadoop.http.staticuser.user="${USER:-hdfs}"
      - HDFS-SITE.XML_hadoop.user.name="${USER:-hdfs}"
    networks:
      - hadoop-net
    volumes:
      - namenode-data:/tmp/hadoop-root/dfs/name

  datanode-1:
    image: apache/hadoop:3.4
    container_name: hadoop-datanode1
    command: ["hdfs", "datanode"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment: *environment
    networks:
      - hadoop-net
    depends_on:
      - namenode
      - resourcemanager
    volumes:
      - datanode1-data:/tmp/hadoop-root/dfs/data

  datanode-2:
    image: apache/hadoop:3.4
    container_name: hadoop-datanode2
    command: ["hdfs", "datanode"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment: *environment
    networks:
      - hadoop-net
    depends_on:
      - namenode
      - resourcemanager
    volumes:
      - datanode2-data:/tmp/hadoop-root/dfs/data

  resourcemanager:
    image: apache/hadoop:3.4
    container_name: hadoop-resourcemanager
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 8088:8088
    networks:
      - hadoop-net
    depends_on:
      - namenode

  nodemanager:
    image: apache/hadoop:3.4
    container_name: hadoop-nodemanager
    command: ["yarn", "nodemanager"]
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - YARN-SITE.XML_yarn.resourcemanager.hostname="resourcemanager"
    networks:
      - hadoop-net
    depends_on:
      - resourcemanager

networks:
  hadoop-net:
    driver: bridge

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data: